### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by har00n-haider** [har00n-haider/threejsProject#1]
- [ ] Why does the touch to destroy not work (Ray casting)
- [ ] Create a loop where may gameobjects can be added (a main gameobject, that generates the the others)
- [ ]  Button to make the thing full screen
- [ ] disable scrolling
- [ ] Lock to portrait view?
