### ISSUE TITLE
KanjiGame ToDo

### ISSUE THREAD

**Issue by har00n-haider** [har00n-haider/threejsProject#2]
### kanji detection
- [x] Make a list of around 10 kanji per level 
- [x] Clean up one Kanji round of play ( no lingering components etc.)
- [x] understand the hierarchy of the main objects in 3d and debug the kanji plane issue
- [x] Do the kanji rendering/input on the near plane of the camera / some other plane floating infront of the camera ( not on the x/y plane)
- [ ] Define a good consistent size of the input area (PC and phones). i.e. it should be in the same location and device pixel size. definitely should fit to screen.
- [x] Add dat gui to play with various settings (e.g. camera zoom, selecting main camera , [pause ](https://stackoverflow.com/questions/38034787/three-js-and-buttons-for-start-and-pause-animation))
- [x] have a second editor camera that has controls associated with it that you can move
- [x] Fix bug on PC/android where the draw gets randomly cancelled

### box cutting
Abandoning this idea as it would take bloody ages, aint nobody got time fo dat!
> - [x] use the csg library to cut a box in half, with a thinner plane box
> > CSG is too slow and current libs don't readily give access to the cut meshes. ditching it
> -  [ ] use the unity package to understand how the mesh cutting works
> - [ ] figure out what is more of a pain in the ass, porting over the mesh cutting code to js or entire project to unity

### Game

- [x] fruit ninja style targets where they take random trajectories through the player view
- [ ] targets should have the English word hover beneath them. Can use [procedural text](https://threejs.org/examples/#webgl_geometry_text).
- [ ] select kanji (stop time)
- [ ] draw kanji that matches the English word
- [ ] take damage if you miss, red explosion
- [ ] green explosion if you pass, some points based on performance (average distance of ref points)
- [ ] timer bar for kanji
- [ ] health bar 
- [ ] Start screen 
- [ ] kanji set selection screen
- [ ] game over screen
- [ ] sound effects
- [ ] music
